name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/testcrud .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/testcrud:latest

  deploy:
    needs: build
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Ensure Docker & Docker Compose are installed
        run: |
          sudo apt update
          sudo apt install -y docker.io docker-compose
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Pull latest Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/testcrud:latest

      - name: Stop and remove old containers
        run: sudo docker-compose down || true

      - name: Create `.env` file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
          echo "PORT=3000" >> .env

      - name: Start services with Docker Compose
        run: sudo docker-compose up -d --force-recreate
